document.write('<style>')
document.write('body {margin: 0}')
document.write('.topnav {font-family: Arial;overflow: hidden;background-color: #313131; width:100%;}')
document.write('.link {float: left;color: #ffffff;text-align: center;padding: 1vh 0.8vw;text-decoration: none;font-size: 0.93vw;font-weight: bold;}')
document.write('.link:hover {background-color: #1e90ff; color: #ffffff;}')
document.write('.logo {height: 4vw;width: 9vw;float: left;}')
document.write('</style>')
document.write('<div class="topnav">')
document.write('  <a href="Home.htm">')
document.write('<img class="logo" src="logo.png" alt="logo">')
document.write('  </a>')
document.write('  <a class="link" href="Shellbags.htm">Shellbags</a>')
document.write('  <a class="link" href="Autorunsc.htm">Autoruns</a>')
document.write('  <a class="link" href="Autorunsc_Without_Windows_Entries.htm">Autoruns Without Windows Entries</a>')
document.write('  <a class="link" href="Dns_Cache.htm">Dns Cache</a>')
document.write('  <a class="link" href="Environment_Variables.htm">Environment Variables</a>')
document.write('  <a class="link" href="Netbios.htm">Netbios</a>')
document.write('  <a class="link" href="Network_Shares.htm">Net Shares</a>')
document.write('  <a class="link" href="Processes.htm">Processes</a>')
document.write('  <a class="link" href="Network_Connections.htm">Network Connections</a>')
document.write('  <a class="link" href="Loaded_Dlls.htm">Loaded Dlls</a>')
document.write('  <a class="link" href="UserAssist.htm">UserAssist</a>')
document.write('  <a class="link" href="Event_Viewer.htm">Event Viewer</a>')
document.write('  <a class="link" href="Port_Forwarding.htm">Port Forwarding</a>')
document.write('  <a class="link" href="Last_Activity.htm">Last Activity</a>')
document.write('  <a class="link" href="Scheduletasks.htm">Schedule Tasks</a>')
document.write('  <a class="link" href="Services.htm">Services</a>')
document.write('  <a class="link" href="Hosts.htm">Hosts File</a>')
document.write('  <a class="link" href="System32_Folder.htm">System32 Folder</a>')
document.write('  <a class="link" href="Windows_Folder.htm">Windows Folder</a>')
document.write('  <a class="link" href="Temp_Folder.htm">Temp Folder</a>')
document.write('  <a class="link" href="Logons.htm">Logons</a>')
document.write('  <a class="link" href="USB_Connections.htm">USB Connections</a>')
document.write('  <a class="link" href="ARP_cache.htm">ARP Cache</a>')
document.write('</div>')